name: wormhole
adopt-info: wormhole
summary: get things from one computer to another, safely
description: |
  This package provides a library and a command-line tool named wormhole, which
  makes it possible to get arbitrary-sized files and directories (or short
  pieces of text) from one computer to another. The two endpoints are identified
  by using identical "wormhole codes": in general, the sending machine generates
  and displays the code, which must then be typed into the receiving machine.

grade: stable
confinement: strict

apps:
  wormhole:
    command: bin/wormhole
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  wormhole:
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version "${last_committed_tag}"
      else
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
    plugin: python
    python-version: python2
    source: https://github.com/warner/magic-wormhole.git
    source-type: git
    build-packages:
      - build-essential
      - python-dev
      - libffi-dev
      - libssl-dev
      - libsodium-dev
